/*
 * Copyright (c) 2008-2009 Kotikalapudi Raghavendra. All Rights Reserved.
 *
 * Licensed under the Creative Commons License Attribution-NonCommercial-ShareAlike 3.0,
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://creativecommons.org/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * DataBuilderStatsu.java
 *
 * Created on Apr 11, 2009, 3:01:58 PM
 */

package ui.builder.data;

import java.awt.Color;
import java.util.Vector;
import jneuralnet.core.preprocessor.AbstractInputPreprocessor;
import jneuralnet.core.preprocessor.AbstractOutputPreprocessor;
import jneuralnet.core.preprocessor.CompoundInputPreprocessor;
import jneuralnet.core.preprocessor.CompoundOutputPreprocessor;
import jneuralnet.core.training.TrainingDataRepository;
import jnnhelper.Configuration;
import org.jdesktop.swingx.painter.MattePainter;
import utilities.MyPainters;

/**
 *
 * @author Ragha
 */
public class DataBuilderStatus extends javax.swing.JPanel
{
    public static final String ID = "Data Builder";

    private static DataBuilderStatus instance;
    public static DataBuilderStatus getInstance()
    {
        return instance;
    }

    /** Creates new form DataBuilderStatsu */
    public DataBuilderStatus()
    {
        initComponents();
        instance = this;
        jXHeader1.setBackgroundPainter(MyPainters.getHeaderPainter());
        jXPanel1.setBackgroundPainter(MyPainters.getSummaryPanelPainter());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalSets = new org.jdesktop.swingx.JXLabel();
        lblTrainingSets = new org.jdesktop.swingx.JXLabel();
        lblvalidationSets = new org.jdesktop.swingx.JXLabel();
        lblTestSets = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXList2 = new org.jdesktop.swingx.JXList();
        jXHeader1 = new org.jdesktop.swingx.JXHeader();

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel6.text")); // NOI18N

        jXPanel1.setBackgroundPainter(new MattePainter(new Color(238, 246, 241)));
        jXPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel4.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel3.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.jLabel2.text")); // NOI18N

        lblTotalSets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalSets.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.lblTotalSets.text")); // NOI18N

        lblTrainingSets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrainingSets.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.lblTrainingSets.text")); // NOI18N

        lblvalidationSets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblvalidationSets.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.lblvalidationSets.text")); // NOI18N

        lblTestSets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTestSets.setText(org.openide.util.NbBundle.getMessage(DataBuilderStatus.class, "DataBuilderStatus.lblTestSets.text")); // NOI18N

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTestSets, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(lblvalidationSets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrainingSets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        jXPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblTestSets, lblTotalSets, lblTrainingSets, lblvalidationSets});

        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTrainingSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblvalidationSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTestSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jXList1);

        jXList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jXList2);

        jXHeader1.setTitle("<html>\n<h3>Data Summary</h3>\n<p>\nShows the summary of data available to the network\n</html>"); // NOI18N
        jXHeader1.setTitleFont(new java.awt.Font("Tahoma", 0, 11));
        jXHeader1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXHeader1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jXPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    }// </editor-fold>//GEN-END:initComponents

    public void refreshStatus()
    {
        //refresh data status...
        TrainingDataRepository tdr = Configuration.getInstance()
                .getNeuralNetwork().getTeacher().getTrainingDataRepository();
        lblTotalSets.setText(tdr.getTotalAvailablePatternSize().toString());
        lblTrainingSets.setText(tdr.getTrainingDataPatternSize().toString());
        lblvalidationSets.setText(tdr.getValidationDataPatternSize().toString());
        lblTestSets.setText(tdr.getTestDataPatternSize().toString());

        //refresh input preprocessor list...        
        Vector<String> vec = new Vector<String>();
        AbstractInputPreprocessor ip = Configuration.getInstance()
                .getNeuralNetwork().getInputPreprocessor();
        if(ip != null) {
            if(ip instanceof CompoundInputPreprocessor) {
                CompoundInputPreprocessor cip = (CompoundInputPreprocessor) ip;
                for(int i=0; i<cip.getPreprocessors().length; i++) {
                    vec.add(i, cip.getPreprocessors()[i].getName());
                }
            }
            else
                vec.add(0, ip.getName());
        }
        jXList1.setListData(vec);

        //refresh output preprocessor list...        
        vec = new Vector<String>();
        AbstractOutputPreprocessor op = Configuration.getInstance()
                .getNeuralNetwork().getOutputPreprocessor();
        if(op != null) {
            if(op instanceof CompoundOutputPreprocessor) {
                CompoundOutputPreprocessor cop = (CompoundOutputPreprocessor) op;
                for(int i=0; i<cop.getPreprocessors().length; i++) {
                    vec.add(i, cop.getPreprocessors()[i].getName());
                }
            }
            else
                vec.add(0, op.getName());
        }
        jXList2.setListData(vec);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXList jXList2;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXLabel lblTestSets;
    private org.jdesktop.swingx.JXLabel lblTotalSets;
    private org.jdesktop.swingx.JXLabel lblTrainingSets;
    private org.jdesktop.swingx.JXLabel lblvalidationSets;
    // End of variables declaration//GEN-END:variables

}
