/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NetworkVisualizer.java
 *
 * Created on Jun 11, 2009, 3:24:26 PM
 */
package org.jnnhelper.ui.networkbuilder;

import java.awt.BorderLayout;
import org.jnnhelper.ui.Configuration;
import org.netbeans.api.visual.graph.GraphScene;

/**
 *
 * @author Ragha
 */
public class NetworkVisualizer extends javax.swing.JPanel
{
    private NetworkVisualizationGraph scene;

    /** Creates new form NetworkVisualizer */
    public NetworkVisualizer() {
        initComponents();
        //Create the GraphSceneImpl:
        scene = new NetworkVisualizationGraph();
        //Add it to the JScrollPane:
        jScrollPane1.setViewportView(scene.createView());
        //Add the SatellitView to the scene:
        add(scene.createSatelliteView(), BorderLayout.WEST);
        instance = this;
    }

    private static NetworkVisualizer instance;
    public static NetworkVisualizer getInstance()
    {
        return instance;
    }

    public void refreshView()
    {
        scene.showNetwork(Configuration.getInstance().getNeuralNetwork(),
                getWidth(), getHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
