/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.jnnhelper.ui.databuilder;

import java.util.logging.Logger;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd="-//org.jnnhelper.ui.databuilder//DataBuilder//EN",
    autostore=false
)
public final class DataBuilderTopComponent extends TopComponent {

    private static DataBuilderTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "DataBuilderTopComponent";
    private final DataBuilderStatus pnlDataBuilderStatus;
    private final DataBuilder pnlDataBuilder;
    private final DataClustering pnlDataClustering;
    private final DataPreprocessing pnlDataPreprocessing;

    public DataBuilderTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(DataBuilderTopComponent.class, "CTL_DataBuilderTopComponent"));
        setToolTipText(NbBundle.getMessage(DataBuilderTopComponent.class, "HINT_DataBuilderTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
	putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
	putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

        pnlDataBuilderStatus = new DataBuilderStatus();
        pnlDataBuilder = new DataBuilder();
        pnlDataClustering = new DataClustering();
        pnlDataPreprocessing = new DataPreprocessing();
        jScrollPane1.setViewportView(pnlDataBuilderStatus);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized DataBuilderTopComponent getDefault() {
        if (instance == null) {
            instance = new DataBuilderTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the DataBuilderTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized DataBuilderTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(DataBuilderTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof DataBuilderTopComponent) {
            return (DataBuilderTopComponent) win;
        }
        Logger.getLogger(DataBuilderTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        DataBuilderTopComponent singleton = DataBuilderTopComponent.getDefault();
        singleton.readPropertiesImpl(p);
        return singleton;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    public void showPanel(String pnlID)
    {
        if(!isOpened())
            open();

        if(pnlID.equals(DataBuilderStatus.ID))
            jScrollPane1.setViewportView(pnlDataBuilderStatus);
        if(pnlID.equals(DataBuilder.ID))
            jScrollPane1.setViewportView(pnlDataBuilder);
        if(pnlID.equals(DataClustering.ID))
            jScrollPane1.setViewportView(pnlDataClustering);
        if(pnlID.equals(DataPreprocessing.ID))
            jScrollPane1.setViewportView(pnlDataPreprocessing);
    }
}
